### ISSUE TITLE
Where do I find my authToken?

### ISSUE THREAD

**Issue by ghost** [lyndsysimon/gab#5]
I tried using my id_token but that isn't working.

**Comment by lyndsysimon** [comment]
It's in the Authorization header sent with every XHR sent by your browser.

Here's a screenshot in Chrome's dev tools of mine (portions distorted for security purposes):

![screen-shot-2017-01-05-at-11 23 20-am](https://cloud.githubusercontent.com/assets/131414/21688190/db884322-d339-11e6-9353-0170ea0043bf.png)

**Comment by imlinus** [comment]
Legendary!

**Comment by imlinus** [comment]
Hi friend, I've stumped upon a problem.
I'm trying to reach https://gab.ai/users/linus via a XHR call (for in browser api call)

I've generated the following token (via php): 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI5NTQ3OSIsImV4cCI6MTQ4NjAxMTMyMn0.e30da1afcb5f53f6597121f829b8b71556bb6c42e10c1a1b5a75fc8c1bfbef8d

I built the string as following:
payload = (user_id, expires)
passkey

Trying to reach my user "linus" @ user_id 95479

Do you have some input on where to progress?

Cheers,
Linus

**Comment by lyndsysimon** [comment]
I'm not sure what you mean when you say you've generated it via PHP?
